import React from 'react';
import { Feather, FontAwesome, MaterialCommunityIcons } from '@expo/vector-icons';

export const Bell = (props: any) => <Feather name="bell" {...props} />;
export const MapPin = (props: any) => <Feather name="map-pin" {...props} />;
export const Ticket = (props: any) => <MaterialCommunityIcons name="ticket-outline" {...props} />;
export const Scan = (props: any) => <Feather name="maximize" {...props} />;
export const Maximize = Scan;
export const Signal = (props: any) => <Feather name="wifi" {...props} />;
export const Wifi = Signal;
export const Users = (props: any) => <Feather name="users" {...props} />;
export const IndianRupee = (props: any) => <FontAwesome name="rupee" {...props} />;
export const Clock = (props: any) => <Feather name="clock" {...props} />;
export const RefreshCw = (props: any) => <Feather name="refresh-cw" {...props} />;
export const RefreshCcw = RefreshCw;
export const RotateCw = RefreshCw;
export const AlertCircle = (props: any) => <Feather name="alert-circle" {...props} />;
export const CircleAlert = AlertCircle;
export const AlertTriangle = (props: any) => <Feather name="alert-triangle" {...props} />;
export const TriangleAlert = AlertTriangle;
export const History = (props: any) => <MaterialCommunityIcons name="history" {...props} />;
export const Bus = (props: any) => <MaterialCommunityIcons name="bus" {...props} />;
export const Truck = Bus;
export const Search = (props: any) => <Feather name="search" {...props} />;
export const QrCode = (props: any) => <MaterialCommunityIcons name="qrcode-scan" {...props} />;
export const ScanQrCode = QrCode;
export const ChevronRight = (props: any) => <Feather name="chevron-right" {...props} />;
export const TrendingUp = (props: any) => <Feather name="trending-up" {...props} />;
export const TrendingDown = (props: any) => <Feather name="trending-down" {...props} />;
export const Download = (props: any) => <Feather name="download" {...props} />;
export const User = (props: any) => <Feather name="user" {...props} />;
export const Shield = (props: any) => <Feather name="shield" {...props} />;
export const Settings = (props: any) => <Feather name="settings" {...props} />;
export const HelpCircle = (props: any) => <Feather name="help-circle" {...props} />;
export const LogOut = (props: any) => <Feather name="log-out" {...props} />;
export const X = (props: any) => <Feather name="x" {...props} />;
export const XSquare = (props: any) => <Feather name="x-square" {...props} />;
export const Zap = (props: any) => <Feather name="zap" {...props} />;
export const Flash = Zap;
export const Home = (props: any) => <Feather name="home" {...props} />;
export const FileText = (props: any) => <Feather name="file-text" {...props} />;
export const File = FileText;
